<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;'); Property::truncate(); DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $properties = [
            [
                'title' => 'Beautiful Downtown Apartment',
                'description' => 'Modern apartment in the heart of downtown with stunning city views, full amenities, and close proximity to restaurants and shopping centers.',
                'price' => 350000,
                'type' => 'residential',
                'location' => 'New York City, New York',
                'country' => 'United States',
                'state' => 'New York',
                'city' => 'New York City',
                'address' => '123 Main Street, Downtown District',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'area' => 1500,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'parking_spaces' => 2,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'John Smith',
                'agent_contact' => '+1 (555) 123-4567',
            ],
            [
                'title' => 'Modern Office Complex',
                'description' => 'Prime commercial space perfect for corporate offices. Features high-speed internet, professional workspace, parking, and modern amenities.',
                'price' => 750000,
                'type' => 'commercial',
                'location' => 'Los Angeles, California',
                'country' => 'United States',
                'state' => 'California',
                'city' => 'Los Angeles',
                'address' => '456 Commerce Avenue, Business Hub',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'area' => 5000,
                'bedrooms' => null,
                'bathrooms' => 4,
                'parking_spaces' => 15,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'Sarah Johnson',
                'agent_contact' => '+1 (555) 234-5678',
            ],
            [
                'title' => 'Spacious Suburban Home',
                'description' => 'Beautiful family home in a quiet suburban neighborhood with large yard, modern kitchen, and excellent schools nearby.',
                'price' => 425000,
                'type' => 'residential',
                'location' => 'Houston, Texas',
                'country' => 'United States',
                'state' => 'Texas',
                'city' => 'Houston',
                'address' => '789 Oak Lane, Quiet Neighborhood',
                'latitude' => 29.7604,
                'longitude' => -95.3698,
                'area' => 2500,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'parking_spaces' => 3,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'Michael Brown',
                'agent_contact' => '+1 (555) 345-6789',
            ],
            [
                'title' => 'Prime Development Land',
                'description' => 'Excellent investment opportunity. Zoned for mixed-use development with great potential for residential or commercial projects.',
                'price' => 500000,
                'type' => 'land',
                'location' => 'Miami, Florida',
                'country' => 'United States',
                'state' => 'Florida',
                'city' => 'Miami',
                'address' => '321 Future Development Way',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
                'area' => 10000,
                'bedrooms' => null,
                'bathrooms' => null,
                'parking_spaces' => null,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'John Smith',
                'agent_contact' => '+1 (555) 123-4567',
            ],
            [
                'title' => 'Luxury Penthouse',
                'description' => 'Stunning penthouse with panoramic views, premium finishes, private balcony, and exclusive building amenities.',
                'price' => 890000,
                'type' => 'residential',
                'location' => 'Chicago, Illinois',
                'country' => 'United States',
                'state' => 'Illinois',
                'city' => 'Chicago',
                'address' => '999 Luxury Heights, Downtown',
                'latitude' => 41.8781,
                'longitude' => -87.6298,
                'area' => 3200,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'parking_spaces' => 3,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'Sarah Johnson',
                'agent_contact' => '+1 (555) 234-5678',
            ],
            [
                'title' => 'Cozy Studio Apartment',
                'description' => 'Perfect starter home or investment property. Recently renovated with modern appliances and neutral decor.',
                'price' => 180000,
                'type' => 'residential',
                'location' => 'Seattle, Washington',
                'country' => 'United States',
                'state' => 'Washington',
                'city' => 'Seattle',
                'address' => '456 Central Park Avenue',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'area' => 650,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_available' => true,
                'agent_name' => 'Michael Brown',
                'agent_contact' => '+1 (555) 345-6789',
            ],
            [
                'title' => 'Retail Shop Space',
                'description' => 'Excellent retail location with high foot traffic. Ideal for boutique, cafe, or any retail business.',
                'price' => 300000,
                'type' => 'commercial',
                'location' => 'San Francisco, California',
                'country' => 'United States',
                'state' => 'California',
                'city' => 'San Francisco',
                'address' => '555 Retail Plaza',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'area' => 2000,
                'bedrooms' => null,
                'bathrooms' => 2,
                'parking_spaces' => 8,
                'is_featured' => false,
                'is_available' => true,
                'agent_name' => 'John Smith',
                'agent_contact' => '+1 (555) 123-4567',
            ],
            [
                'title' => 'Waterfront Property',
                'description' => 'Stunning waterfront residence with direct beach access, modern architecture, and breathtaking water views.',
                'price' => 1200000,
                'type' => 'residential',
                'location' => 'Miami Beach, Florida',
                'country' => 'United States',
                'state' => 'Florida',
                'city' => 'Miami Beach',
                'address' => '100 Ocean Drive, Beach Front',
                'latitude' => 25.7907,
                'longitude' => -80.1300,
                'area' => 4000,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'parking_spaces' => 4,
                'is_featured' => true,
                'is_available' => true,
                'agent_name' => 'Sarah Johnson',
                'agent_contact' => '+1 (555) 234-5678',
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
